{
 "title": "Article Dispatcher",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Request Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Add Article Request Counts",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nine_article_dispatcher_request_latency_micro_count{endpoint=\"add_article\",error=\"false\"}"
    }
   ]
  },
  {
   "title": "Get Article Request Count",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 7, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nine_article_dispatcher_request_latency_micro_count{endpoint=\"get_article\",error=\"false\"}"
    }
   ]
  },
  {
   "title": "Filter Article Request Count",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 7, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nine_article_dispatcher_request_latency_micro_count{endpoint=\"filter_article\",error=\"false\"}"
    }
   ]
  },
  { "title": "Request Latency ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Add Article Request Latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(nine_article_dispatcher_request_latency_micro_sum{endpoint=\"add_article\",error=\"false\"}[5m])/rate(nine_article_dispatcher_request_latency_micro_count{endpoint=\"add_article\",error=\"false\"}[5m])"
    },
    {
     "expr": "rate(nine_article_dispatcher_request_latency_micro_sum{endpoint=\"add_article\",error=\"true\"}[5m])/rate(nine_article_dispatcher_request_latency_micro_count{endpoint=\"add_article\",error=\"true\"}[5m])"
    }
   ]
  },
  {
   "title": "Get Article Request Latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(nine_article_dispatcher_request_latency_micro_sum{endpoint=\"get_article\",error=\"false\"}[5m])/rate(nine_article_dispatcher_request_latency_micro_count{endpoint=\"get_article\",error=\"false\"}[5m])"
    },
    {
     "expr": "rate(nine_article_dispatcher_request_latency_micro_sum{endpoint=\"get_article\",error=\"true\"}[5m])/rate(nine_article_dispatcher_request_latency_micro_count{endpoint=\"get_article\",error=\"true\"}[5m])"
    }
   ]
  },
  {
   "title": "Filter Article Request Latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(nine_article_dispatcher_request_latency_micro_sum{endpoint=\"filter_article\",error=\"false\"}[5m])/rate(nine_article_dispatcher_request_latency_micro_count{endpoint=\"filter_article\",error=\"false\"}[5m])"
    },
    {
     "expr": "rate(nine_article_dispatcher_request_latency_micro_sum{endpoint=\"filter_article\",error=\"true\"}[5m])/rate(nine_article_dispatcher_request_latency_micro_count{endpoint=\"filter_article\",error=\"true\"}[5m])"
    }
   ]
  }
 ]
}